datadog:
  datadog:
    apiKeyExistingSecret: datadog-secret
    clusterName: petclinic
    site: datadoghq.com

    logs:
      enabled: true
      containerCollectAll: true

    operator:
      enabled: false

  agents:
    enabled: true

  clusterAgent:
    enabled: true
    env:
      - name: DD_KUBERNETES_APISERVER_CLIENT_QPS
        value: "50"
      - name: DD_KUBERNETES_APISERVER_CLIENT_BURST
        value: "100"
